generate_video_clips_task:
  description: >
    使用VEO3 API生成所有视频片段：

    **项目信息：**
    - 项目ID：{project_id}
    - 视频标题：{video_title}
    - 总时长：{total_duration}秒

    **视频提示词列表：**
    {video_prompts}

    **角色参考图像：**
    {character_images}

    **生成要求：**
    1. 为每个提示词生成对应的5秒视频片段
    2. 确保所有片段保持角色外观的一致性
    3. 使用提供的角色参考图像维持视觉连贯性
    4. 优化VEO3生成参数以获得最佳质量
    5. 处理生成过程中的错误和重试逻辑
    6. 验证每个生成的视频片段的质量和时长
    7. 将生成的视频文件保存到项目目录
    8. 记录生成进度和状态信息

    **技术规范：**
    - 分辨率：1080p (1920x1080)
    - 帧率：24fps
    - 格式：MP4
    - 编码：H.264
    - 时长：每片段5秒

    **错误处理：**
    - 实施指数退避重试策略
    - 处理API限制和超时
    - 生成失败时提供备用方案
    - 记录详细的错误日志

    请按顺序处理每个视频提示词，生成对应的视频片段，并确保整体质量和一致性。

  expected_output: >
    完成所有视频片段的生成，输出包括：
    - 每个视频片段的本地文件路径
    - 生成状态报告（成功/失败/重试次数）
    - 视频质量验证结果
    - 角色一致性检查结果
    - 总体生成统计信息
    - 为视频编辑准备的片段清单

assemble_final_video_task:
  description: >
    将生成的视频片段拼接成最终完整视频：

    **输入材料：**
    - 项目ID：{project_id}
    - 视频片段列表：{video_clips}
    - 目标总时长：{total_duration}秒
    - 视频标题：{video_title}

    **拼接要求：**
    1. 按照故事顺序拼接所有视频片段
    2. 添加平滑的转场效果（淡入淡出或切换）
    3. 确保音频连续性和同步
    4. 优化整体视频质量和压缩
    5. 添加开头标题和结尾字幕（如需要）
    6. 处理片段之间的时长调整
    7. 应用色彩校正和统一化处理
    8. 生成多种格式和分辨率版本

    **技术规范：**
    - 主输出格式：MP4 (H.264)
    - 分辨率：1080p
    - 帧率：24fps
    - 音频：AAC 44.1kHz
    - 比特率：自适应优化

    **输出版本：**
    1. 高质量版本（用于下载和存档）
    2. 网络优化版本（用于在线播放）
    3. 移动设备版本（较小文件大小）

    **质量控制：**
    - 检查视频完整性和播放流畅性
    - 验证音视频同步
    - 确保无损坏帧或异常
    - 生成视频预览和缩略图

    请完成视频拼接和后期处理，输出专业质量的最终视频文件。

  expected_output: >
    完整的最终视频文件，包括：
    - 主视频文件路径（高质量版本）
    - 网络优化版本文件路径
    - 移动版本文件路径
    - 视频元数据信息（时长、分辨率、文件大小）
    - 质量检查报告
    - 缩略图和预览图像
    - 视频制作统计信息
    - 可用于分享的下载链接